# Generated by Django 4.2 on 2023-04-04 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghere', '0004_alter_post_thumbnail_alter_post_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 16, 44, 4, 351884), null=True),
        ),
    ]
