# Generated by Django 4.2 on 2023-04-05 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghere', '0006_alter_post_image_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 5, 8, 48, 11, 280270), null=True),
        ),
    ]
